
import Swal from "sweetalert2";
import "../../styles/home.css";
import withReactContent from "sweetalert2-react-content";
import { checkConnection, setHistorial } from "./rpaSlice";
const MySwal = withReactContent(Swal);

const Toast = MySwal.mixin({
  toast: true,
  position: "top",
  iconColor: "white",
  customClass: {
    popup: "colored-toast",
  },
  showConfirmButton: false,
  timer: 2500,
  timerProgressBar: true,
});

export const startCheckConnection = (id_tribunal) => {
  return async (dispatch) => {
    try {
      const f = new FormData();
      f.append("idTribunal", id_tribunal);
      
      const error_connection = 'error';
      dispatch(checkConnection(error_connection));
      if (error_connection === "success") {
        Toast.fire({
          icon: error_connection,
          title: `Conexión exitosa con el equipo remoto.`,
        });
      } else {
        Toast.fire({
          icon: error_connection,
          title: `No se pudo establecer conexión con el equipo remoto.(API desconectada)`,
        });
      }
    } catch (error) {
      console.log(error);
    }
  };
};

export const startGetHistorial = (id_tribunal) => {
  return async (dispatch) => {
    try {
      const f = new FormData();
      f.append("id_tribunal", id_tribunal);
      const historial_emulation = [
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "false",
            "fecha": "28/11/2023",
            "id_area": 55,
            "id_historial": 552,
            "id_robot": 114,
            "nombre_robot": "Informe Activos Fijos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "false",
            "fecha": "28/11/2023",
            "id_area": 55,
            "id_historial": 555,
            "id_robot": 114,
            "nombre_robot": "Informe Activos Fijos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "false",
            "fecha": "28/11/2023",
            "id_area": 55,
            "id_historial": 553,
            "id_robot": 114,
            "nombre_robot": "Informe Activos Fijos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "false",
            "fecha": "28/11/2023",
            "id_area": 55,
            "id_historial": 554,
            "id_robot": 114,
            "nombre_robot": "Informe Activos Fijos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "false",
            "fecha": "28/11/2023",
            "id_area": 55,
            "id_historial": 556,
            "id_robot": 114,
            "nombre_robot": "Informe Activos Fijos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "false",
            "fecha": "28/11/2023",
            "id_area": 55,
            "id_historial": 557,
            "id_robot": 114,
            "nombre_robot": "Informe Activos Fijos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "28/11/2023",
            "id_area": 55,
            "id_historial": 558,
            "id_robot": 114,
            "nombre_robot": "Informe Activos Fijos",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "28/11/2023",
            "id_area": 55,
            "id_historial": 559,
            "id_robot": 114,
            "nombre_robot": "Informe Activos Fijos",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "23/11/2023",
            "id_area": 134,
            "id_historial": 550,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "23/11/2023",
            "id_area": 55,
            "id_historial": 551,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "22/11/2023",
            "id_area": 134,
            "id_historial": 549,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "20/11/2023",
            "id_area": 134,
            "id_historial": 548,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "17/11/2023",
            "id_area": 134,
            "id_historial": 547,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "16/11/2023",
            "id_area": 134,
            "id_historial": 546,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "15/11/2023",
            "id_area": 134,
            "id_historial": 545,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "14/11/2023",
            "id_area": 134,
            "id_historial": 544,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "10/11/2023",
            "id_area": 134,
            "id_historial": 543,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "9/11/2023",
            "id_area": 134,
            "id_historial": 542,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "8/11/2023",
            "id_area": 134,
            "id_historial": 541,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "7/11/2023",
            "id_area": 134,
            "id_historial": 540,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "6/11/2023",
            "id_area": 134,
            "id_historial": 538,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "6/11/2023",
            "id_area": 134,
            "id_historial": 539,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "3/11/2023",
            "id_area": 134,
            "id_historial": 537,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "2/11/2023",
            "id_area": 134,
            "id_historial": 536,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "false",
            "fecha": "31/10/2023",
            "id_area": 134,
            "id_historial": 535,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "26/10/2023",
            "id_area": 134,
            "id_historial": 534,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "25/10/2023",
            "id_area": 134,
            "id_historial": 533,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "24/10/2023",
            "id_area": 55,
            "id_historial": 531,
            "id_robot": 114,
            "nombre_robot": "Informe Activos Fijos",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "24/10/2023",
            "id_area": 134,
            "id_historial": 530,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "24/10/2023",
            "id_area": 55,
            "id_historial": 532,
            "id_robot": 114,
            "nombre_robot": "Informe Activos Fijos",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "20/10/2023",
            "id_area": 134,
            "id_historial": 497,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "19/10/2023",
            "id_area": 134,
            "id_historial": 496,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "18/10/2023",
            "id_area": 55,
            "id_historial": 491,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "18/10/2023",
            "id_area": 55,
            "id_historial": 490,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "18/10/2023",
            "id_area": 55,
            "id_historial": 489,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "18/10/2023",
            "id_area": 55,
            "id_historial": 488,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "18/10/2023",
            "id_area": 55,
            "id_historial": 487,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "18/10/2023",
            "id_area": 55,
            "id_historial": 486,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "18/10/2023",
            "id_area": 55,
            "id_historial": 485,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "18/10/2023",
            "id_area": 55,
            "id_historial": 484,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "18/10/2023",
            "id_area": 55,
            "id_historial": 483,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "18/10/2023",
            "id_area": 134,
            "id_historial": 462,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "18/10/2023",
            "id_area": 55,
            "id_historial": 495,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "18/10/2023",
            "id_area": 55,
            "id_historial": 494,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "18/10/2023",
            "id_area": 55,
            "id_historial": 493,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "18/10/2023",
            "id_area": 55,
            "id_historial": 492,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "17/10/2023",
            "id_area": 134,
            "id_historial": 461,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "13/10/2023",
            "id_area": 134,
            "id_historial": 460,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "12/10/2023",
            "id_area": 134,
            "id_historial": 459,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "11/10/2023",
            "id_area": 134,
            "id_historial": 458,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "10/10/2023",
            "id_area": 134,
            "id_historial": 455,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "10/10/2023",
            "id_area": 55,
            "id_historial": 456,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "10/10/2023",
            "id_area": 55,
            "id_historial": 457,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "6/10/2023",
            "id_area": 134,
            "id_historial": 454,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "5/10/2023",
            "id_area": 134,
            "id_historial": 453,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 448,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 134,
            "id_historial": 432,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "4/10/2023",
            "id_area": 134,
            "id_historial": 433,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 434,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 435,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 436,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 437,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 438,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 439,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 440,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 441,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 442,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 443,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 444,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 445,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 446,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 447,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 449,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 450,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 451,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "4/10/2023",
            "id_area": 55,
            "id_historial": 452,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "3/10/2023",
            "id_area": 134,
            "id_historial": 431,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "2/10/2023",
            "id_area": 134,
            "id_historial": 430,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "29/9/2023",
            "id_area": 134,
            "id_historial": 429,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "28/9/2023",
            "id_area": 134,
            "id_historial": 428,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "27/9/2023",
            "id_area": 134,
            "id_historial": 427,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "26/9/2023",
            "id_area": 55,
            "id_historial": 426,
            "id_robot": 114,
            "nombre_robot": "Informe Activos Fijos",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "26/9/2023",
            "id_area": 134,
            "id_historial": 425,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "25/9/2023",
            "id_area": 55,
            "id_historial": 424,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "25/9/2023",
            "id_area": 134,
            "id_historial": 423,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "13/9/2023",
            "id_area": 55,
            "id_historial": 413,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "13/9/2023",
            "id_area": 55,
            "id_historial": 414,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "13/9/2023",
            "id_area": 55,
            "id_historial": 422,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "13/9/2023",
            "id_area": 55,
            "id_historial": 421,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "13/9/2023",
            "id_area": 55,
            "id_historial": 420,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "13/9/2023",
            "id_area": 55,
            "id_historial": 419,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "13/9/2023",
            "id_area": 55,
            "id_historial": 418,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "13/9/2023",
            "id_area": 55,
            "id_historial": 417,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "13/9/2023",
            "id_area": 55,
            "id_historial": 416,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "13/9/2023",
            "id_area": 55,
            "id_historial": 415,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "12/9/2023",
            "id_area": 134,
            "id_historial": 412,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "11/9/2023",
            "id_area": 134,
            "id_historial": 411,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "8/9/2023",
            "id_area": 134,
            "id_historial": 410,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "7/9/2023",
            "id_area": 134,
            "id_historial": 409,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "6/9/2023",
            "id_area": 134,
            "id_historial": 408,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "false",
            "fecha": "6/9/2023",
            "id_area": 134,
            "id_historial": 407,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "1/9/2023",
            "id_area": 134,
            "id_historial": 406,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "31/8/2023",
            "id_area": 134,
            "id_historial": 405,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "30/8/2023",
            "id_area": 134,
            "id_historial": 404,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "false",
            "fecha": "29/8/2023",
            "id_area": 134,
            "id_historial": 401,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "29/8/2023",
            "id_area": 134,
            "id_historial": 403,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "false",
            "fecha": "29/8/2023",
            "id_area": 134,
            "id_historial": 402,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "false",
            "fecha": "29/8/2023",
            "id_area": 134,
            "id_historial": 400,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Bonilla",
            "correo": "hbonilla@pjud.cl",
            "estado_final": "true",
            "fecha": "28/8/2023",
            "id_area": 55,
            "id_historial": 399,
            "id_robot": 114,
            "nombre_robot": "Informe Activos Fijos",
            "nombre_usuario": "Héctor",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "24/8/2023",
            "id_area": 134,
            "id_historial": 398,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "23/8/2023",
            "id_area": 134,
            "id_historial": 397,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "23/8/2023",
            "id_area": 55,
            "id_historial": 396,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Bonilla",
            "correo": "hbonilla@pjud.cl",
            "estado_final": "true",
            "fecha": "22/8/2023",
            "id_area": 55,
            "id_historial": 391,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Héctor",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "22/8/2023",
            "id_area": 55,
            "id_historial": 395,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "22/8/2023",
            "id_area": 55,
            "id_historial": 394,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "true",
            "fecha": "22/8/2023",
            "id_area": 55,
            "id_historial": 393,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Mardones",
            "correo": "agmardones@pjud.cl",
            "estado_final": "false",
            "fecha": "22/8/2023",
            "id_area": 55,
            "id_historial": 392,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Alfonso",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Coronado",
            "correo": "mcoronado@pjud.cl",
            "estado_final": "true",
            "fecha": "22/8/2023",
            "id_area": 134,
            "id_historial": 390,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Consuelo",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Bonilla",
            "correo": "hbonilla@pjud.cl",
            "estado_final": "true",
            "fecha": "21/8/2023",
            "id_area": 55,
            "id_historial": 389,
            "id_robot": 113,
            "nombre_robot": "Gestion de SII",
            "nombre_usuario": "Héctor",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        },
        {
            "apellido_usuario": "Tiznado",
            "correo": "ftiznado@pjud.cl",
            "estado_final": "true",
            "fecha": "21/8/2023",
            "id_area": 134,
            "id_historial": 388,
            "id_robot": 97,
            "nombre_robot": "Ingreso de exhortos",
            "nombre_usuario": "Felipe",
            "tribunal": "Juzgado de Letras y Garantia de Pucon"
        }
    ]
      
      dispatch(setHistorial(historial_emulation))
    } catch (error) {
      console.log(error);
    }
  };
};
